config/routes.rb
Rails.application.routes.draw do
  get 'people/index'
  get 'people/new'
  get 'people/create'
  get 'people/edit'
  get 'people/update'
  get 'people/destroy'
  get 'home/index'

  resources :people

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index

    @a = Person.all

  end

  def new
  end

  def create

    person = Person.new(params_people)

    person.save

    redirect_to people_index_path

  end

  def edit
  end

  def update
    Person.find(params[:id]).update(params_people)

    redirect_to people_index_path

  end

  def destroy

    Person.find(params[:id]).destroy

    redirect_to people_index_path

  end

  private
  def params_people
    params.require(:person).permit(:name, :age)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Basico</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/create.html.erb
<h1>People#create</h1>
<p>Find me in app/views/people/create.html.erb</p>

app/views/people/destroy.html.erb
<h1>People#destroy</h1>
<p>Find me in app/views/people/destroy.html.erb</p>

app/views/people/edit.html.erb
<h1>People#edit</h1>
<p>Find me in app/views/people/edit.html.erb</p>

<%= form_for Person.find(params[:id]) do |p| %>

  <%= p.label 'Nome:' %>
  <%= p.text_field :name %>

  <%= p.label 'Idade:' %>
  <%= p.number_field :age %>

  <br>

  <%= p.submit 'Criar pessoa' %>

<% end %>

app/views/people/index.html.erb
<h1>Título</h1>

<% @a.each do |person| %>

<%= person.name %> - <%= person.age %> - <%= link_to 'Editar', edit_person_path(person.id) %> - <%= link_to 'Remover', person, method: :delete %>

  <br>

<% end %>

<%= link_to 'Criar pessoa', people_new_path %>

app/views/people/new.html.erb
<h1>People#new</h1>
<p>Find me in app/views/people/new.html.erb</p>



<%= form_for Person.new do |p| %>

  <%= p.label 'Nome:' %>
  <%= p.text_field :name %>

  <%= p.label 'Idade:' %>
  <%= p.number_field :age %>

  <br>

  <%= p.submit 'Criar pessoa' %>

<% end %>

<%= button_to 'Voltar', people_index_path, method: :get %>


<!--Nova pessoa-->

<!--Nome:-->
<!--Idade:-->

<!--<form>-->

<!--  <label>Nome:</label>-->
<!--  <input type="text">-->

<!--</form>-->

app/views/people/update.html.erb
<h1>People#update</h1>
<p>Find me in app/views/people/update.html.erb</p>